service: tooling-s3-sqs

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'


plugins:
  - serverless-localstack
  - serverless-offline
  - serverless-mocha-plugin


custom:
  serverless-offline:
    useChildProcess: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
