service: image-analysis

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - rekognition: DetectLabels
      Resources: *
    - Effect: "Allow"
      Action:
        - translate: TranslateText
      Resource: "*"

functions:
  img_analysis:
    handler: handler.main
    events:
      - http:
          path: analyse
          method: get
